version: '3'

networks:
  backend-net:
    driver: bridge

services:
  system-sys-app-api:
    build:
      context: .
    container_name: system-sys-app-api
    ports:
      - "8000:8000"
    user: "${DUID}:${DGID}"
    networks:
      - backend-net
    depends_on:
      - system-sys-app-db
    env_file: ./app/app/local.env
    volumes:
      - "./app:/src/app/app"
    command: /src/app/entrypoints/docker-entrypoint-dev.sh

  system-sys-app-db:
    image: postgres:13
    container_name: system-sys-app-db
    ports:
      - "5432:5432"
    networks:
      - backend-net
    volumes:
      - "/docker/data/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  system-sys-app-rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-net
    environment:
      - RABBITMQ_DEFAULT_USER=caio
      - RABBITMQ_DEFAULT_PASS=123456

  system-sys-app-worker:
    build:
      context: .
    container_name: system-sys-app-worker
    depends_on:
      - system-sys-app-rabbitmq
      - system-sys-app-db
    networks:
      - backend-net
    env_file:
      - ./app/app/local.env
    command:
      - /src/app/entrypoints/docker-entrypoint-celery.sh

  system-sys-app-redis:
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - backend-net
