# Generated by Django 3.2 on 2023-06-16 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('cpf', models.IntegerField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{11}$')], verbose_name='cpf')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
