# Generated by Django 4.2.2 on 2023-06-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
